In [2]:
import pandas as pd
import streamlit as st
from theme_manager import ThemeManager  # Classe para carregar o tema
from data_loader import DataLoader  # Classe para carregar os dados
from filter_menu import FilterMenu  # Classe para renderizar o menu de filtros
from dashboard import Dashboard  # Classe para gerar os gráficos do dashboard

In [3]:
# Carregando os dados
dataloader = DataLoader('Dataset')

Todos os arquivos de vendas foram combinados com sucesso.
Todas as tabelas foram relacionadas com sucesso.

In [5]:
dataloader.location

     LOCATION_ID Country State                    City   Latitude  Longitude
0      LOBA00474      BR    BA              Alagoinhas -12.103680 -38.355090
1      LOMG00475      BR    MG                 Alfenas -21.466445 -45.996509
2      LOMG00476      BR    MG                 Alfenas -21.466855 -45.984828
3      LOGO00487      BR    GO                Anápolis -16.424773 -48.993149
4      LOGO00488      BR    GO                Anápolis -16.336820 -48.987640
...          ...     ...   ...                     ...        ...        ...
1953   LOES02423      BR    ES                 Vitória -20.329778 -40.340957
1954   LOPE02427      BR    PE  Vitória De Santo Antão  -8.156200 -35.357200
1955   LOSP02428      BR    SP              Votorantim -23.603200 -47.496200
1956   LOSC02429      BR    SC                 Xanxerê -26.890800 -52.439300
1957   LOSC02430      BR    SC                   Xaxim -26.996200 -52.572200

[1958 rows x 6 columns]

In [3]:
final_data.head()

,Order Id,Product Id,Prod. Costs,Rent Costs,Sales Date,Total Cost,Customer Id,Volume (LB),Volume,Industry,...,CAT_ID,BL_ID,BL_DESC,Plant Name,Plant_Country,Plant_State,Plant_City,Plant_Latitude,Plant_Longitude,Plant Manager
0,32170082,BL01-CA03-1101,308.28,0.0,2019-01-15,178.33,4564.0,0,0,5020,...,CA03,BL01,Lubrificantes,Sorocaba,BR,SP,Sorocaba,-23.43386,-47.39249,Peter Stephen
1,32176102,BL01-CA08-1078,384.78,0.0,2019-01-03,22.74,4564.0,7757,0,7140,...,CA08,BL01,Lubrificantes,Sorocaba,BR,SP,Sorocaba,-23.43386,-47.39249,Peter Stephen
2,32176246,BL01-CA08-1078,384.78,0.0,2019-01-14,23.54,4564.0,8088,0,7140,...,CA08,BL01,Lubrificantes,Sorocaba,BR,SP,Sorocaba,-23.43386,-47.39249,Peter Stephen
3,32176265,BL01-CA08-1078,192.39,0.0,2019-01-15,11.77,4564.0,4044,0,7140,...,CA08,BL01,Lubrificantes,Sorocaba,BR,SP,Sorocaba,-23.43386,-47.39249,Peter Stephen
4,32171963,BL01-CA03-1040,13.80,0.0,2019-01-17,8.37,4564.0,60,0,3085,...,CA03,BL01,Lubrificantes,Sorocaba,BR,SP,Sorocaba,-23.43386,-47.39249,Peter Stephen

In [3]:
# Renderização do menu de filtros
filter_menu = FilterMenu(final_data)
# filtered_data, cards_data = filter_menu.render()